update filter and add logging tests #ROBO-2954
UiPath/FreeRDP pull request #11
Opened 2023-04-24 12:22 UTC by mihainradu

2023-04-27 11:13 UTC, eduard-dumitru requested changes
I would approve if it weren't for the explicit **Cdecl** dilemma in `NativeInterface.cs`, which I suspect was forgotten from older experiments.

Even though it might work, it introduces a surprise factor in the unlikely event that we would augment the parameters and flow outside the registry range.

2023-04-27 11:13 UTC, eduard-dumitru commented on UiPath.FreeRdpClient/UiPath.FreeRdpClient.Tests/TestInfra/TestHost.cs
> +            loggingBuilder.SetMinimumLevel(LogLevel.Trace);
👍

2023-06-29 08:47 UTC, danutboanta commented on UiPath.FreeRdpClient/UiPath.FreeRdpClient/Internals/Logging.cs
> +    internal void EnsureNativeLogsForwarding()
As time the EnableNativeLogsForwarding is done in constructor, EnsureNativeLogsForwarding is not needed (also _logsForwardingEnabled not needed)

2023-06-29 09:56 UTC, mihainradu commented
> I would approve if it weren't for the explicit **Cdecl** dilemma in `NativeInterface.cs`, which I suspect was forgotten from older experiments.
> 
> Even though it might work, it introduces a surprise factor in the unlikely event that we would augment the parameters and flow outside the registry range.

asta a fost rezolvata... dar nu mi-e clar cum sa o marchez

2023-06-29 09:58 UTC, merged